runtime: nodejs20
env: standard

entrypoint: node server.js

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
  max_instances: 5

env_variables:
  NODE_ENV: production

network:
  session_affinity: false
